name: image_text_segmentation
channels:
  - conda-forge
  - defaults
  - ak_93
  - ecrop
dependencies:
  - python=3.6
  - numpy==1.13.1
  - scikit-learn
  - opencv
  - scikit-image
  - numba
  - shapely
